/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc2021

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import kotlin.test.assertNotNull

class AdventOfCodeTest : StringSpec({
    "lets start advent of Code" {
        val classUnderTest = App()
        classUnderTest.greeting shouldBe "Merry Christmas!"
    }
})
