/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc2021

import day1.DayOne

class App {
    val greeting: String
        get() {
            return "Merry Christmas!"
        }
}

fun main() {
    println(App().greeting)
    DayOne().executeDayOnePartOne()
    DayOne().executeDayOnePartTwo()
}
