/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc2021

import day1.DayOne
import day2.DayTwo
import day3.DayThree
import day4.DayFour
import day5.DayFive
import day6.DaySix
import day7.DaySeven
import day8.DayEight
import day9.DayNine

class App {
    val greeting: String
        get() {
            return "Merry Christmas!"
        }
}

fun main() {
    println(App().greeting)

    dayOne()
    dayTwo()
    dayThree()
    dayFour()
    dayFive()
    daySix()
    daySeven()
    dayEight()
    dayNine()
}

fun dayNine() {
    println("Welcome to Day Nine!")

    DayNine().findBasinsOnHeightMap(
        readInput("daynineinput.txt")
            .toList()
    )
}

fun dayEight() {
    println("Welcome to Day Eight!")

    DayEight().countUniqueDigitsInOutput(
        readInput("dayeightinput.txt")
            .map { it.split(" | ")[1] }
            .toList()
    )
}

fun daySeven() {
    println("Welcome to Day Seven!")
    DaySeven().lowestFuelConsumption(
        readInput("dayseven.txt")[0].split(",").map { it.toInt() }.toList()
    )
}

fun daySix() {
    println("Welcome to Day Six!")
    DaySix().countOfLanternfishesAfterDays(
        readInput("daysixinput.txt")[0].split(",").map { it.toInt() },
        256
    )
}

fun dayFive() {
    println("Welcome to Day Five")
    val parseInputToLinePoints = DayFive().parseInputToLinePoints(
        readInput("dayfiveinput.txt")
    )
    DayFive().calculateOverlappingPoints(parseInputToLinePoints)
}

fun dayFour() {
    println("Welcome to Day Three!")
    DayFour().calculateBingoScore(
        readInput("dayfour-drawnumbers.txt")[0],
        readInput("dayfour-boards.txt")
    )
}

fun dayThree() {
    println("Welcome to Day Three!")
    val input = readInput("daythreeinput.txt")
    DayThree().calculatePowerConsumption(
        input
    )
    DayThree().calculateLifeSupportRating(
        input
    )
}

fun dayTwo() {
    println("Welcome to Day Two!")
    DayTwo().calculateDepthAndHPosMultiplied(
        readInput("daytwoinput.txt")
    )
}

private fun dayOne() {
    println("Welcome to Day One!")
    DayOne().calculateIncreasedValues(
        readInput("dayoneinput.txt")
            .map { it.toInt() }
            .toIntArray()
    )

    println("Welcome to Day One - Part 2!")
    DayOne().calculateAmountMeasurementWindowsIncreased(
        readInput("dayoneinput2.txt")
            .map { it.toInt() }
            .toIntArray()
    )
}


fun readInput(resourceName: String): List<String> {
    val readLines = App::class.java
        .classLoader
        .getResourceAsStream(resourceName)!!
        .bufferedReader()
        .readLines()
    return readLines
}
